background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 3
    noise = 0.02
    contrast = 1.0
    brightness = 0.6
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 1
    dots_size = 0.2
    outer_color = rgb(d8d5c0)
    inner_color = rgb(262626)
    font_color = rgb(d8d5c0)
    fade_on_empty = false
    placeholder_text = <span foreground="##727169">Password...</span>
    rounding = 0
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgba(216, 213, 192, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = rgba(200, 192, 147, 1.0)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 130
    halign = center
    valign = center
}
